import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import { Analytics } from "@vercel/analytics/next";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin-ext"],
});

const helveticaRegular = localFont({
  src: "./fonts/Helvetica.woff",
  variable: "--font-helvetica-regular",
});

const helveticaBold = localFont({
  src: "./fonts/Helvetica-Bold.woff",
  variable: "--font-helvetica-bold",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${helveticaRegular.variable} ${helveticaBold.variable} antialiased`}
      >
        {children}
        <Analytics />
      </body>
    </html>
  );
}
